# Generated by Django 5.2 on 2025-04-21 15:34

import core_apps.app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(199)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(validators=[core_apps.app.models.validate_publication_year]),
        ),
    ]
